controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

location_index:
    path: /locations
    controller: App\Controller\LocationController::index

measurement_index:
    path: /measurements
    controller: App\Controller\MeasurementController::index

app_logout:
    path: /logout
    methods: GET

register_user:
    path: /register-user
    controller: App\Controller\RegisterController::index

app_weather:
    path: /weather/{city}/{countryCode}
    controller: App\Controller\WeatherController::city